INSERT INTO expense (amount, type, category, description, date) VALUES (85000.00, 'Income', 'Salary', 'August Salary', '2025-09-01');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 15000.00, 'Expense', 'Rent', 'Rent for September', '2025-09-01');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 799.00, 'Expense', 'Utilities', 'Internet Bill', '2025-09-02');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 10000.00, 'Income', 'Freelance', 'Web design project payment', '2025-09-03');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 4500.75, 'Expense', 'Groceries', 'Weekly grocery run', '2025-09-03');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 1850.50, 'Expense', 'Utilities', 'Electricity Bill for August', '2025-09-04');
INSERT INTO expense (amount, type, category, description, date) VALUES (2200.00, 'Expense', 'Food', 'Dinner at a local restaurant', '2025-09-05');
INSERT INTO expense (amount, type, category, description, date) VALUES (1250.00, 'Income', 'Investments', 'Dividend from stocks', '2025-09-05');
INSERT INTO expense (amount, type, category, description, date) VALUES (2000.00, 'Expense', 'Transport', 'Fuel for car', '2025-09-06');
INSERT INTO expense (amount, type, category, description, date) VALUES (650.00, 'Expense', 'Entertainment', 'Movie tickets for two', '2025-09-06');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 3200.00, 'Expense', 'Shopping', 'Bought new shoes', '2025-09-06');
