INSERT INTO expense (amount, type, category, description, date) VALUES (1000.00, 'Income', 'Salary', 'August Salary', '2025-09-01');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 100.00, 'Expense', 'Rent', 'Rent for September', '2025-09-01');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 100.00, 'Expense', 'Utilities', 'Internet Bill', '2025-09-02');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 1000.00, 'Income', 'Freelance', 'Web design project payment', '2025-09-03');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 100.00, 'Expense', 'Groceries', 'Weekly grocery run', '2025-09-03');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 100.00, 'Expense', 'Utilities', 'Electricity Bill for August', '2025-09-04');
INSERT INTO expense (amount, type, category, description, date) VALUES (100.00, 'Expense', 'Food', 'Dinner at a local restaurant', '2025-09-05');
INSERT INTO expense (amount, type, category, description, date) VALUES (1000.00, 'Income', 'Investments', 'Dividend from stocks', '2025-09-05');
INSERT INTO expense (amount, type, category, description, date) VALUES (100.00, 'Expense', 'Transport', 'Fuel for car', '2025-09-06');
INSERT INTO expense (amount, type, category, description, date) VALUES (100.00, 'Expense', 'Entertainment', 'Movie tickets for two', '2025-09-06');
INSERT INTO expense (amount, type, category, description, date) VALUES ( 100.00, 'Expense', 'Shopping', 'Bought new shoes', '2025-09-06');
